# Generated by Django 5.1.2 on 2024-11-24 13:24

import ActivosFijos.models.anexo_articulo
import ActivosFijos.models.articulos
import ActivosFijos.models.cronograma
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos_Articulos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdAnexo', models.AutoField(primary_key=True, serialize=False)),
                ('Archivo', models.FileField(blank=True, null=True, upload_to=ActivosFijos.models.anexo_articulo.cargar_anexo_path, verbose_name='foto del producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Areas_Trabajo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_Area', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Observacion', models.CharField(blank=True, max_length=400, null=True)),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_Articulo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('Serie', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('Costo', models.DecimalField(blank=True, decimal_places=3, max_digits=40, null=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to=ActivosFijos.models.articulos.Cargar_imagenes_articulos_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulos_OrdenServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdArticulo_OS', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('Costo', models.DecimalField(blank=True, decimal_places=3, max_digits=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_realizacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('Novedad', models.TextField(blank=True, null=True)),
                ('Actualizacion', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to=ActivosFijos.models.cronograma.documetos_bitacora_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria_Articulo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_GrupoArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=400, null=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CronogramaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_programada', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_Actividad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_EstadoActividad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=500)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
            ],
            options={
                'verbose_name': 'EstadoActividad',
                'verbose_name_plural': 'EstadoActividad',
                'ordering': ['Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Estado_Articulo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_EstadoArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'EstadoArticulo',
                'verbose_name_plural': 'EstadoArticulo',
                'ordering': ['Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Hoja_Vida_Articulos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdHojaVidaArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('Novedad', models.TextField(blank=True, null=True)),
                ('Actualizacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdInventario', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimineto_Tipos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_TipoMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=400, null=True)),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marca',
                'ordering': ['Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdOrdenServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('FechaAutorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('Costo', models.DecimalField(blank=True, decimal_places=3, max_digits=40, null=True)),
                ('Observaciones_adicionales', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('prueba', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_Presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Observacion', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad', models.IntegerField()),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
                ('Fecha_Aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha creación')),
                ('Fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='fecha Cierre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_TipoArticulo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'TipoArticulo',
                'verbose_name_plural': 'TipoArticulo',
                'ordering': ['Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoRegistroInventario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Id_TipoRegistroInventario', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250, unique=True)),
                ('Activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'TipoRegistroInventario',
                'verbose_name_plural': 'TipoRegistroInventario',
                'ordering': ['Descripcion'],
            },
        ),
    ]
