# Generated by Django 5.1.2 on 2024-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Macroprocesos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdCargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['-IdCargo'],
            },
        ),
        migrations.CreateModel(
            name='Dias_Laborales_cargos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdHorarioCargo', models.AutoField(primary_key=True, serialize=False)),
                ('Dias_Laborales', models.CharField(blank=True, max_length=100, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'HorarioCargo',
                'verbose_name_plural': 'HorariosCargos',
                'ordering': ['-IdHorarioCargo'],
            },
        ),
        migrations.CreateModel(
            name='Horario_cargos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdHorario', models.AutoField(primary_key=True, serialize=False)),
                ('Horario', models.CharField(blank=True, max_length=100, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000)),
                ('Descanso_Diurno', models.TimeField(blank=True, null=True)),
                ('Almuerzo', models.TimeField(blank=True, null=True)),
                ('Descanso_Nocturno', models.TimeField(blank=True, null=True)),
                ('es_estandar', models.BooleanField(default=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['-IdHorario'],
            },
        ),
        migrations.CreateModel(
            name='MacroProcesos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdMacroProcesos', models.AutoField(primary_key=True, serialize=False)),
                ('MacroProcesos', models.CharField(blank=True, max_length=100, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'MacroProcesos',
                'verbose_name_plural': 'MacroProcesos',
                'ordering': ['-IdMacroProcesos'],
            },
        ),
        migrations.CreateModel(
            name='proceso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdProceso', models.AutoField(primary_key=True, serialize=False)),
                ('Proceso', models.CharField(blank=True, max_length=100, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['-IdProceso'],
            },
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('Seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'ordering': ['-IdSeccion'],
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdTipoPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('TipoPersonal', models.CharField(blank=True, max_length=100, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'TipoPersonal',
                'verbose_name_plural': 'TipoPersonal',
                'ordering': ['-IdTipoPersonal'],
            },
        ),
    ]
