# Generated by Django 5.1.3 on 2024-12-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico_paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Medico-Paquete',
                'verbose_name_plural': 'Medicos-Paquetes',
                'ordering': ['medico'],
            },
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'ordering': ['tercero'],
            },
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaquetesServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Paquete-Servicio',
                'verbose_name_plural': 'Paquetes-Servicios',
                'ordering': ['paquete'],
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
