from django import forms
from RrHh.models.hoja_vida import Hoja_Vida
import datetime
now = datetime.datetime.now()


class HojaVidaForm(forms.ModelForm):
    class Meta:
        model = Hoja_Vida
        fields = [
            'nombre',
            'apellido',
            'tipo_documentoFK',
            'sexo',
            'numero_identificacion',
            'nacionalidad_FK',
            'departamento_FK',
            'Municipio_FK',
            'pais_residencia',
            'dep_residencia',
            'mun_residencia',
            'Barrio_FK',
            'fecha_expedicion',
            'lugar_expedicion',
            'Libreta_Militar',
            'lugar_expedicion_libreta',
            'fecha_expedicion_libreta',
            'pais_expedicion_libreta',
            'Distrito_Libreta',
            'Clase_libreta',
            'Tarjeta_Profesional',
            'fecha_nacimiento',
            'direccion',
            'telefono',
            'email',
            'profesion',
            'hijos',
            'vivienda_FK',
            'tipo_vivienda_FK',
            'contacto_emergencia',
            'parentesco',
            'telefono_emergencia',
            'fondo_pensionFK',
            'fondo_cesantiasFK',
            'CajaCompensacionFK',
            'eps',
            'talla_camisa',
            'talla_pantalon',
            'talla_zapatos',
            'grupo_sanguineoFK',
            'estado_civilFK',
            'habilidades',
            'linkedin',
            'twitter',
            'facebook',
            'instagram',
            'whatsapp',
            'website',
            'imagen',
            'upload_cv',

            ]
        labels = {
            'nombre': 'Nombres',
            'apellido': 'Apellidos',
            'tipo_documentoFK': 'Tipo Documento',
            'sexo': 'Sexo',
            'numero_identificacion': 'Numero de Identificacion',
            'nacionalidad_FK': 'Nacionalidad',
            'departamento_FK': 'Departamento',
            'Municipio_FK': 'Municipio',
            'pais_residencia': 'Pais de Residencia',
            'dep_residencia': 'Departamento de Residencia',
            'mun_residencia': 'Municipio de Residencia',
            'Barrio_FK': 'Barrio',
            'fecha_expedicion': 'Fecha de Expedicion',
            'lugar_expedicion': 'Lugar de Expedicion',
            'Libreta_Militar': 'Libreta Militar',
            'lugar_expedicion_libreta': 'Lugar de expedicion libreta',
            'fecha_expedicion_libreta': 'Fecha de expedicion libreta',
            'pais_expedicion_libreta': 'Pais de expedicion libreta',
            'Distrito_Libreta': 'Distrito de libreta',
            'Clase_libreta': 'Clase de libreta',
            'Tarjeta_Profesional': 'Tarjeta Profesional',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'direccion': 'Dirección',
            'telefono': 'Telefono',
            'email': 'Email',
            'profesion': 'Profesion',
            'hijos': 'Hijos',
            'vivienda_FK': 'Vivienda',
            'tipo_vivienda_FK': 'Tipo de Vivienda',
            'contacto_emergencia': 'Contacto de Emergencia',
            'parentesco': 'Parentesco',
            'telefono_emergencia': 'Telefono de Emergencia',
            'fondo_pensionFK': 'Fondo de Pension',
            'fondo_cesantiasFK': 'Fondo de Cesantias',
            'CajaCompensacionFK': 'Caja de Compensacion',
            'eps': 'EPS',
            'talla_camisa': 'Talla de Camisa',
            'talla_pantalon': 'Talla de Pantalon',
            'talla_zapatos': 'Talla de Zapatos',
            'grupo_sanguineoFK': 'Grupo Sanguineo',
            'estado_civilFK': 'Estado Civil',
            'habilidades': 'Habilidades',
            'linkedin': 'Linkedin',
            'twitter': 'Twitter',
            'facebook': 'Facebook',
            'instagram': 'Instagram',
            'whatsapp': 'Whatsapp',
            'website': 'Website',
            'imagen': 'Imagen',
            'upload_cv': 'Cargar CV',
        }
        
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_documentoFK': forms.Select(attrs={'class': 'form-control select2'}),
            'sexo': forms.Select(attrs={'class': 'form-control select2'}),
            'numero_identificacion': forms.TextInput(attrs={'class': 'form-control'}),
            'nacionalidad_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'departamento_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'Municipio_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'pais_residencia': forms.Select(attrs={'class': 'form-control select2'}),
            'dep_residencia': forms.Select(attrs={'class': 'form-control select2'}),
            'mun_residencia': forms.Select(attrs={'class': 'form-control select2'}),
            'Barrio_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'fecha_expedicion': forms.DateInput(attrs={'type': 'date', 'id': 'start', 'name': 'trip-start', 'value': str(now), 'min': '1900-01-01',  'class': 'form-control '}),
            'lugar_expedicion': forms.Select(attrs={'class': 'form-control select2',}),
            'Libreta_Militar': forms.TextInput(attrs={'class': 'form-control'}),
            'lugar_expedicion_libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_expedicion_libreta': forms.DateInput(attrs={'type': 'date', 'id': 'start', 'name': 'trip-start', 'value': str(now), 'min': '1900-01-01',  'class': 'form-control '}),
            'pais_expedicion_libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'Distrito_Libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'Clase_libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'Tarjeta_Profesional': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date', 'id': 'start', 'name': 'trip-start', 'value': str(now), 'min': '1900-01-01',  'class': 'form-control '}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'profesion': forms.TextInput(attrs={'class': 'form-control'}),
            'hijos': forms.TextInput(attrs={'class': 'form-control'}),
            'vivienda_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'tipo_vivienda_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'contacto_emergencia': forms.TextInput(attrs={'class': 'form-control'}),
            'parentesco': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono_emergencia': forms.TextInput(attrs={'class': 'form-control'}),
            'fondo_pensionFK': forms.Select(attrs={'class': 'form-control select2'}),
            'fondo_cesantiasFK': forms.Select(attrs={'class': 'form-control select2'}),
            'CajaCompensacionFK': forms.Select(attrs={'class': 'form-control select2'}),
            'eps': forms.Select(attrs={'class': 'form-control select2'}),
            'talla_camisa': forms.TextInput(attrs={'class': 'form-control'}),
            'talla_pantalon': forms.TextInput(attrs={'class': 'form-control'}),
            'talla_zapatos': forms.TextInput(attrs={'class': 'form-control'}),
            'grupo_sanguineoFK': forms.Select(attrs={'class': 'form-control select2'}),
            'estado_civilFK': forms.Select(attrs={'class': 'form-control select2'}),
            'habilidades': forms.TextInput(attrs={'class': 'form-control'}),
            'linkedin': forms.TextInput(attrs={'class': 'form-control'}),
            'twitter': forms.TextInput(attrs={'class': 'form-control'}),
            'facebook': forms.TextInput(attrs={'class': 'form-control'}),
            'instagram': forms.TextInput(attrs={'class': 'form-control'}),
            'whatsapp': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
            'upload_cv': forms.FileInput(attrs={'class': 'form-control'}),
            }

class HojaVida_UpdateForm(forms.ModelForm):
    class Meta:
        model = Hoja_Vida
        fields = [
            'nombre',
            'apellido',
            'tipo_documentoFK',
            'sexo',
            'numero_identificacion',
            'nacionalidad_FK',
            'Municipio_FK',
            'Barrio_FK',
            'fecha_expedicion',
            'lugar_expedicion',
            'Libreta_Militar',
            'lugar_expedicion_libreta',
            'fecha_expedicion_libreta',
            'pais_expedicion_libreta',
            'Distrito_Libreta',
            'Clase_libreta',
            'Tarjeta_Profesional',
            'fecha_nacimiento',
            'direccion',
            'telefono',
            'email',
            'profesion',
            'hijos',
            'vivienda_FK',
            'tipo_vivienda_FK',
            'contacto_emergencia',
            'parentesco',
            'telefono_emergencia',
            'fondo_pensionFK',
            'fondo_cesantiasFK',
            'CajaCompensacionFK',
            'eps',
            'talla_camisa',
            'talla_pantalon',
            'talla_zapatos',
            'grupo_sanguineoFK',
            'estado_civilFK',
            'habilidades',
            'linkedin',
            'twitter',
            'facebook',
            'instagram',
            'whatsapp',
            'website',
            'imagen',
            'upload_cv',

            ]
        labels = {
            'nombre': 'Nombres',
            'apellido': 'Apellidos',
            'tipo_documentoFK': 'Tipo Documento',
            'sexo': 'Sexo',
            'numero_identificacion': 'Numero de Identificacion',
            'nacionalidad_FK': 'Nacionalidad',
            'Municipio_FK': 'Municipio',
            'Barrio_FK': 'Barrio',
            'fecha_expedicion': 'Fecha de Expedicion',
            'lugar_expedicion': 'Lugar de Expedicion',
            'Libreta_Militar': 'Libreta Militar',
            'lugar_expedicion_libreta': 'Lugar de expedicion libreta',
            'fecha_expedicion_libreta': 'Fecha de expedicion libreta',
            'pais_expedicion_libreta': 'Pais de expedicion libreta',
            'Distrito_Libreta': 'Distrito de libreta',
            'Clase_libreta': 'Clase de libreta',
            'Tarjeta_Profesional': 'Tarjeta Profesional',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'direccion': 'Dirección',
            'telefono': 'Telefono',
            'email': 'Email',
            'profesion': 'Profesion',
            'hijos': 'Hijos',
            'vivienda_FK': 'Vivienda',
            'tipo_vivienda_FK': 'Tipo de Vivienda',
            'contacto_emergencia': 'Contacto de Emergencia',
            'parentesco': 'Parentesco',
            'telefono_emergencia': 'Telefono de Emergencia',
            'fondo_pensionFK': 'Fondo de Pension',
            'fondo_cesantiasFK': 'Fondo de Cesantias',
            'CajaCompensacionFK': 'Caja de Compensacion',
            'eps': 'EPS',
            'talla_camisa': 'Talla de Camisa',
            'talla_pantalon': 'Talla de Pantalon',
            'talla_zapatos': 'Talla de Zapatos',
            'grupo_sanguineoFK': 'Grupo Sanguineo',
            'estado_civilFK': 'Estado Civil',
            'habilidades': 'Habilidades',
            'linkedin': 'Linkedin',
            'twitter': 'Twitter',
            'facebook': 'Facebook',
            'instagram': 'Instagram',
            'whatsapp': 'Whatsapp',
            'website': 'Website',
            'imagen': 'Imagen',
            'upload_cv': 'Cargar CV',
        }
        
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_documentoFK': forms.Select(attrs={'class': 'form-control select2'}),
            'sexo': forms.Select(attrs={'class': 'form-control select2'}),
            'numero_identificacion': forms.TextInput(attrs={'class': 'form-control'}),
            'nacionalidad_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'Municipio_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'Barrio_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'fecha_expedicion': forms.TextInput(attrs={'type': 'date', 'id': 'start', 'name': 'trip-start', 'value': str(now), 'min': '1900-01-01',  'class': 'form-control '}),
            'lugar_expedicion': forms.Select(attrs={'class': 'form-control select2',}),
            'Libreta_Militar': forms.TextInput(attrs={'class': 'form-control'}),
            'lugar_expedicion_libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_expedicion_libreta': forms.TextInput(attrs={'type': 'date', 'id': 'start', 'name': 'trip-start', 'value': str(now), 'min': '1900-01-01',  'class': 'form-control '}),
            'pais_expedicion_libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'Distrito_Libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'Clase_libreta': forms.TextInput(attrs={'class': 'form-control'}),
            'Tarjeta_Profesional': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.TextInput(attrs={'type': 'date', 'id': 'start', 'name': 'trip-start', 'value': str(now), 'min': '1900-01-01',  'class': 'form-control '}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'profesion': forms.TextInput(attrs={'class': 'form-control'}),
            'hijos': forms.TextInput(attrs={'class': 'form-control'}),
            'vivienda_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'tipo_vivienda_FK': forms.Select(attrs={'class': 'form-control select2'}),
            'contacto_emergencia': forms.TextInput(attrs={'class': 'form-control'}),
            'parentesco': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono_emergencia': forms.TextInput(attrs={'class': 'form-control'}),
            'fondo_pensionFK': forms.Select(attrs={'class': 'form-control select2'}),
            'fondo_cesantiasFK': forms.Select(attrs={'class': 'form-control select2'}),
            'CajaCompensacionFK': forms.Select(attrs={'class': 'form-control select2'}),
            'eps': forms.Select(attrs={'class': 'form-control select2'}),
            'talla_camisa': forms.TextInput(attrs={'class': 'form-control'}),
            'talla_pantalon': forms.TextInput(attrs={'class': 'form-control'}),
            'talla_zapatos': forms.TextInput(attrs={'class': 'form-control'}),
            'grupo_sanguineoFK': forms.Select(attrs={'class': 'form-control select2'}),
            'estado_civilFK': forms.Select(attrs={'class': 'form-control select2'}),
            'habilidades': forms.TextInput(attrs={'class': 'form-control'}),
            'linkedin': forms.TextInput(attrs={'class': 'form-control'}),
            'twitter': forms.TextInput(attrs={'class': 'form-control'}),
            'facebook': forms.TextInput(attrs={'class': 'form-control'}),
            'instagram': forms.TextInput(attrs={'class': 'form-control'}),
            'whatsapp': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
            'upload_cv': forms.FileInput(attrs={'class': 'form-control'}),
            }