# Generated by Django 5.1.2 on 2024-11-24 13:24

import RrHh.models.contrato_laboral
import RrHh.models.hoja_vida
import RrHh.models.llamado_atencion
import RrHh.models.retiro_cesantias
import RrHh.models.vacaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizar_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de Actualizacion')),
                ('salario_anterior', models.TextField(blank=True, null=True)),
                ('salario_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_anterior', models.DateTimeField(auto_now_add=True)),
                ('fecha_nueva', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ActualizacionContrato',
                'verbose_name_plural': 'ActualizacionContrato',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Auxilio_No_Prestacional',
            fields=[
                ('IdAuxilio', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auxilio No Prestacional',
                'verbose_name_plural': 'Auxilio No Prestacionales',
                'ordering': ['-IdAuxilio'],
            },
        ),
        migrations.CreateModel(
            name='Caja_Compensacion',
            fields=[
                ('IdCaja', models.AutoField(primary_key=True, serialize=False)),
                ('Caja', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CajaCompensacion',
                'verbose_name_plural': 'CajaCompensacion',
                'ordering': ['Caja'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargo',
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='Contrato_Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio contrato')),
                ('fecha_inicio_laboral', models.DateField(verbose_name='Fecha de Inicio Labores')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Contrato')),
                ('tiempo_contrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meses de contrato')),
                ('CentFormacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Centro de formacion')),
                ('Prog_Formacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Programa de formacion')),
                ('grupo_formacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Grupo de formacion')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=40)),
                ('fecha_renuncia', models.DateField(blank=True, null=True, verbose_name='Fecha de Renuncia')),
                ('fecha_notificacion_renuncia', models.DateField(blank=True, null=True, verbose_name='Fecha de Notificacion Renuncia')),
                ('carta_renuncia', models.FileField(blank=True, null=True, upload_to=RrHh.models.contrato_laboral.upload_renuncia, verbose_name='Carta de Renuncia')),
                ('fecha_despido', models.DateField(blank=True, null=True, verbose_name='Fecha de Despido')),
                ('motivo_fin_contrato', models.TextField(blank=True, null=True, verbose_name='Motivo Fin de Contrato')),
            ],
            options={
                'verbose_name': 'ContratoLaboral',
                'verbose_name_plural': 'ContratoLaboral',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Creacion_Documentos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdDocumentos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_vacacion', models.DateField(blank=True, null=True)),
                ('fecha_fin_vacacion', models.DateField(blank=True, null=True)),
                ('dias_vacaciones', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio_alternativa', models.DateField(blank=True, null=True)),
                ('fecha_fin_alternativa', models.DateField(blank=True, null=True)),
                ('dias_alternativo', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('accion_irregular', models.TextField(blank=True, null=True)),
                ('reportes_anexos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-IdDocumentos'],
            },
        ),
        migrations.CreateModel(
            name='Cuestionario_Descargos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('idcuestionario_descargos', models.AutoField(primary_key=True, serialize=False)),
                ('preguntas', models.CharField(blank=True, max_length=300, null=True)),
                ('respuestas', models.CharField(blank=True, max_length=300, null=True)),
                ('anexos', models.FileField(blank=True, null=True, upload_to=RrHh.models.llamado_atencion.upload_to_anexos)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descargos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('iddescargos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_descargo', models.DateField()),
                ('acciones', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descuentos_Adicionales',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdDescuentos', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Descuentos Adicionales',
                'verbose_name_plural': 'Descuentos Adicionales',
                'ordering': ['-IdDescuentos'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdEducacion', models.AutoField(primary_key=True, serialize=False)),
                ('institucion_EDU', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_EDU', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_EDU', models.IntegerField(blank=True, null=True)),
                ('TextoUnidad_EDU', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_EDU', models.DateField(blank=True, null=True)),
                ('fecha_fin_EDU', models.DateField(blank=True, null=True)),
                ('upload_docs_EDU', models.FileField(blank=True, null=True, upload_to=RrHh.models.hoja_vida.upload_to_hv)),
            ],
            options={
                'verbose_name': 'Educacion',
                'verbose_name_plural': 'Educacion',
                'ordering': ['-IdEducacion'],
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('EPS', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS',
                'ordering': ['EPS'],
            },
        ),
        migrations.CreateModel(
            name='estado_civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'estado_civil',
                'verbose_name_plural': 'estado_civil',
                'ordering': ['Estado'],
            },
        ),
        migrations.CreateModel(
            name='estado_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'estado_contrato',
                'verbose_name_plural': 'estado_contrato',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='estado_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEstadoSolicitud', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'estado_solicitud',
                'verbose_name_plural': 'estado_solicitud',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='experiencia_laboral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdExperiencia_Laboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_EXP', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_EXP', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_EXP', models.DateField(blank=True, null=True)),
                ('fecha_fin_EXP', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experiencia_Laboral',
                'verbose_name_plural': 'Experiencia_Laboral',
                'ordering': ['-IdExperiencia_Laboral'],
            },
        ),
        migrations.CreateModel(
            name='fondo_pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'fondo_pension',
                'verbose_name_plural': 'fondo_pension',
                'ordering': ['fondo'],
            },
        ),
        migrations.CreateModel(
            name='Formato_Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_formato', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_formato', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='fecha de aprobacion')),
                ('divulgacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Formato Carta',
                'verbose_name_plural': 'Formatos Cartas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo_Familiar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdGrupo_Familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_GF', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_GF', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_GF', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento_GF', models.DateField(blank=True, null=True, verbose_name='')),
                ('numero_identificacion_GF', models.CharField(blank=True, max_length=50, null=True)),
                ('anexo_GF', models.FileField(blank=True, null=True, upload_to=RrHh.models.hoja_vida.upload_to_hv)),
            ],
            options={
                'verbose_name': 'Grupo_Familia',
                'verbose_name_plural': 'Grupo_Familia',
                'ordering': ['-IdGrupo_Familiar'],
            },
        ),
        migrations.CreateModel(
            name='Grupo_Sanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'GrupoSanguineo',
                'verbose_name_plural': 'GrupoSanguineo',
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='Hoja_Vida',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdHojaVida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('Libreta_Militar', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_expedicion_libreta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expedicion_libreta', models.DateField(blank=True, null=True)),
                ('Distrito_Libreta', models.CharField(blank=True, max_length=100, null=True)),
                ('Clase_libreta', models.CharField(blank=True, max_length=100, null=True)),
                ('Tarjeta_Profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('hijos', models.IntegerField(blank=True, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('talla_camisa', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_zapatos', models.CharField(blank=True, max_length=10, null=True)),
                ('programa_formacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Programa de formacion')),
                ('codigo_ficha', models.CharField(blank=True, max_length=5, null=True)),
                ('CentroFormacion', models.CharField(default='SIN ASIGNAR', max_length=50)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, default='img/profile/user-1.jpg', null=True, upload_to=RrHh.models.hoja_vida.upload_to_hv)),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to=RrHh.models.hoja_vida.upload_to_hv)),
            ],
            options={
                'verbose_name': 'Hoja_Vida',
                'verbose_name_plural': 'Hoja_Vida',
                'ordering': ['nombre', 'apellido', 'numero_identificacion'],
            },
        ),
        migrations.CreateModel(
            name='Llamado_Atencion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('idllamado_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_infraccion', models.DateField()),
                ('acciones', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Novedades_Nomina',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Novedad Nomina',
                'verbose_name_plural': 'Novedades Nomina',
                'ordering': ['-IdNovedad'],
            },
        ),
        migrations.CreateModel(
            name='Permiso_Laboral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_solicitada', models.DateField()),
                ('tiempo_solicitado_horas', models.IntegerField()),
                ('fundamentacion', models.TextField(blank=True, null=True)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('otro_permiso', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permiso Laboral',
                'verbose_name_plural': 'Permisos Laborales',
                'ordering': ['-IdPermiso'],
            },
        ),
        migrations.CreateModel(
            name='Registro_Carta_Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Carta Laboral',
                'verbose_name_plural': 'Registros Cartas Laborales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Retiro_Cesantias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdRetiroCesantias', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_retiro', models.DateField()),
                ('motivo_retiro', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('File', models.FileField(blank=True, null=True, upload_to=RrHh.models.retiro_cesantias.upload_to_cesantias)),
            ],
            options={
                'verbose_name': 'Retiro Cesantias',
                'verbose_name_plural': 'Retiros Cesantias',
                'ordering': ['-IdRetiroCesantias'],
            },
        ),
        migrations.CreateModel(
            name='Retiro_Laboral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdRetiro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_retiro', models.DateField()),
                ('motivo_retiro', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'ordering': ['-IdRetiro'],
            },
        ),
        migrations.CreateModel(
            name='RodamientoNoPrestacional',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdRodamiento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rodamiento No Prestacional',
                'verbose_name_plural': 'Rodamiento No Prestacionales',
                'ordering': ['-IdRodamiento'],
            },
        ),
        migrations.CreateModel(
            name='soportes_contrato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('idsoportes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_soporte', models.CharField(max_length=100)),
                ('soporte', models.FileField(blank=True, null=True, upload_to=RrHh.models.contrato_laboral.upload_renuncia)),
            ],
            options={
                'verbose_name': 'SoporteContrato',
                'verbose_name_plural': 'SoporteContrato',
                'ordering': ['-idsoportes'],
            },
        ),
        migrations.CreateModel(
            name='tipo_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipo_contrato',
                'verbose_name_plural': 'tipo_contrato',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Formato_Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Formato Carta',
                'verbose_name_plural': 'Tipos Formatos Cartas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Novedad',
            fields=[
                ('IdTipoNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNovedad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoNovedad',
                'verbose_name_plural': 'TipoNovedad',
                'ordering': ['TipoNovedad'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Permiso',
            fields=[
                ('IdTipoPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('TipoPermiso', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoPermiso',
                'verbose_name_plural': 'TipoPermiso',
                'ordering': ['TipoPermiso'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Retiro_Cesantias',
            fields=[
                ('IdTipoRetiroCesantias', models.AutoField(primary_key=True, serialize=False)),
                ('TipoRetiroCesantias', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoRetiroCesantias',
                'verbose_name_plural': 'TipoRetiroCesantias',
                'ordering': ['TipoRetiroCesantias'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Vivienda',
            fields=[
                ('IdTipoVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('TipoVivienda', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoVivienda',
                'verbose_name_plural': 'TipoVivienda',
                'ordering': ['TipoVivienda'],
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('IdSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio_alternativa', models.DateField(blank=True, null=True)),
                ('fecha_fin_alternativa', models.DateField(blank=True, null=True)),
                ('dias_alternativo', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio_laboral', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=RrHh.models.vacaciones.upload_pdf)),
            ],
            options={
                'verbose_name': 'Solicitud de vacaciones',
                'verbose_name_plural': 'Solicitudes de vacaciones',
                'ordering': ['-IdSolicitud'],
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('IdVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('Vivienda', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Vivienda',
                'ordering': ['Vivienda'],
            },
        ),
    ]
