# Generated by Django 5.1.2 on 2024-11-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MacroProcesos', '0002_initial'),
        ('RrHh', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizar_contrato',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualizar_contrato',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auxilio_no_prestacional',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador_auxilio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.cargo'),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='cargo_macro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MacroProcesos.cargo_macroprocesos'),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.datosiniciales'),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='empresa_formacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.terceros'),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualizar_contrato',
            name='Contrato_Laboral_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.contrato_laboral'),
        ),
        migrations.AddField(
            model_name='creacion_documentos',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creacion_documentos',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creacion_documentos',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuestionario_descargos',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuestionario_descargos',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descargos',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descargos',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuestionario_descargos',
            name='Descargos_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cuestionario_del_Descargos', to='RrHh.descargos'),
        ),
        migrations.AddField(
            model_name='descuentos_adicionales',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentos_adicionales',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentos_adicionales',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador_descuentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educacion',
            name='pais_EDU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='shared.paises'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educacion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='estado_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_contrato', to='RrHh.estado_contrato'),
        ),
        migrations.AddField(
            model_name='actualizar_contrato',
            name='estado_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.estado_contrato'),
        ),
        migrations.AddField(
            model_name='creacion_documentos',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_creacion_documento', to='RrHh.estado_solicitud'),
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formato_carta',
            name='aprobaado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formato_carta',
            name='elaborado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos_elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formato_carta',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formato_carta',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_familiar',
            name='sexo_FK_GF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.sexo'),
        ),
        migrations.AddField(
            model_name='grupo_familiar',
            name='tipo_documento_GF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.tipo_documento'),
        ),
        migrations.AddField(
            model_name='grupo_familiar',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_familiar',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='Barrio_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.barrio'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='CajaCompensacionFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.caja_compensacion'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='Municipio_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='shared.municipios'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='dep_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_residencia', to='shared.departamentos'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='departamento_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.departamentos'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.eps'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='estado_civilFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.estado_civil'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='fondo_cesantiasFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fondo_cesantiasFK', to='RrHh.fondo_pension'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='fondo_pensionFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fondo_pensionFK', to='RrHh.fondo_pension'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='grupo_sanguineoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.grupo_sanguineo'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='lugar_expedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugar_expedicion_cedula', to='shared.municipios'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='mun_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_residencia', to='shared.municipios'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='nacionalidad_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.paises'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='pais_expedicion_libreta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_expedicion_libretaFK', to='shared.paises'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='pais_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_residencia', to='shared.paises'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.sexo'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='tipo_documentoFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tipo_documento'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_familiar',
            name='empleado_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_familia', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='hoja_vida_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_laboral', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='hoja_vida_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='descuentos_adicionales',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='descargos',
            name='autorizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Descargos_Autorizado_por', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='creacion_documentos',
            name='propietario_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='hoja_vida_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_laboral', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='auxilio_no_prestacional',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='llamado_atencion',
            name='Autorizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Llamado_Autorizado_por', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='llamado_atencion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colaborador_Infractor', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='llamado_atencion',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamado_atencion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descargos',
            name='Llamado_Atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Descargos_Llamado_Atencion', to='RrHh.llamado_atencion'),
        ),
        migrations.AddField(
            model_name='novedades_nomina',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='novedades_nomina',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedades_nomina',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedades_nomina',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador_novedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='estado_FK',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='RrHh.estado_solicitud'),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='solicitante_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solicitante_del_permiso', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registro_carta_laboral',
            name='contrato_laboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_carta_laboral', to='RrHh.contrato_laboral'),
        ),
        migrations.AddField(
            model_name='registro_carta_laboral',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registro_carta_laboral',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiro_cesantias',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='retiro_cesantias',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiro_cesantias',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiro_cesantias',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador_retiro_cesantias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiro_laboral',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='retiro_laboral',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiro_laboral',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retiro_laboral',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador_retiro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodamientonoprestacional',
            name='colaborador_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='rodamientonoprestacional',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodamientonoprestacional',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodamientonoprestacional',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validador_rodamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soportes_contrato',
            name='Contrato_Laboral_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.contrato_laboral'),
        ),
        migrations.AddField(
            model_name='soportes_contrato',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soportes_contrato',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato_laboral',
            name='tipo_contratoFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_contrato'),
        ),
        migrations.AddField(
            model_name='tipo_formato_carta',
            name='TipoUsuario_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.tipo_usuario'),
        ),
        migrations.AddField(
            model_name='registro_carta_laboral',
            name='tipo_cartaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_formato_carta'),
        ),
        migrations.AddField(
            model_name='formato_carta',
            name='tipo_formato_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_formato_carta'),
        ),
        migrations.AddField(
            model_name='creacion_documentos',
            name='Tipo_Formato_CartaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_formato_carta'),
        ),
        migrations.AddField(
            model_name='novedades_nomina',
            name='tipo_novedadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_novedad'),
        ),
        migrations.AddField(
            model_name='permiso_laboral',
            name='tipo_permisoFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_permiso'),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='tipo_vivienda_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.tipo_vivienda'),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='colaborador_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_vacaciones', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='estado',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_solicitud_vacaciones', to='RrHh.estado_solicitud'),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefe_inmediato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoja_vida',
            name='vivienda_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RrHh.vivienda'),
        ),
    ]
