# Generated by Django 5.1.2 on 2024-11-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RrHh', '0002_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_formato_carta',
            name='TipoUsuario_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_formato_carta', to='shared.tipo_usuario'),
        ),
    ]
