# Generated by Django 5.1.2 on 2024-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('empleado', models.TextField()),
                ('id_biometrico', models.IntegerField()),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='AuxilioNoPrestacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'AuxilioNoPrestacional',
                'verbose_name_plural': 'AuxilioNoPrestacional',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CampoAdicionalLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'CampoAdicionalLiquidacion',
                'verbose_name_plural': 'CampoAdicionalLiquidacion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Descuento', 'Descuento')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conceptos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.FloatField()),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionHorasExtras',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'ConfiguracionHorasExtras',
                'verbose_name_plural': 'ConfiguracionHorasExtras',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CuentaAuxiliar',
                'verbose_name_plural': 'CuentaAuxiliar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CuentaAuxiliar',
                'verbose_name_plural': 'CuentaAuxiliar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CuentaMayor',
                'verbose_name_plural': 'CuentaMayor',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DatosFinancierosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('banco', models.CharField(max_length=255)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DatosFinancieros',
                'verbose_name_plural': 'DatosFinancieros',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'DescuentoAdicional',
                'verbose_name_plural': 'DescuentoAdicional',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GrupoCuenta',
                'verbose_name_plural': 'GrupoCuenta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Naturaleza',
                'verbose_name_plural': 'Naturaleza',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NovedadNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('horas_extra_normal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extra_nocturna', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extra_dominical_diurna', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extra_dominical_nocturna', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extra_festivo_diurno', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extra_festivo_nocturno', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_permiso_laboral', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_llegada_tarde', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vacaciones', models.BooleanField(default=False)),
                ('suspensiones', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NovedadNomina',
                'verbose_name_plural': 'NovedadesNomina',
            },
        ),
        migrations.CreateModel(
            name='RodamNoPresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'RodamNoPresta',
                'verbose_name_plural': 'RodamNoPresta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RutaVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ruta', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'RutaVisita',
                'verbose_name_plural': 'RutaVisita',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'SubCuenta',
                'verbose_name_plural': 'SubCuenta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tabla_Precios_Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('kmh', models.CharField(max_length=255, verbose_name='Kilometros Recorrido')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'TablaPreciosRutas',
                'verbose_name_plural': 'TablaPreciosRutas',
                'ordering': ['-id'],
            },
        ),
    ]
