# Generated by Django 5.1.2 on 2024-11-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contabilidad', '0001_initial'),
        ('RrHh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auxilionoprestacional',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aux_No_Prest', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='auxilionoprestacional',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auxilionoprestacional',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campoadicionalliquidacion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Adicional_Liquidacion', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concepto',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conceptos',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conceptos',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionhorasextras',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionhorasextras',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionnomina',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionnomina',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentaauxiliar',
            name='cuentadetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_auxiliares', to='Contabilidad.cuentadetalle'),
        ),
        migrations.AddField(
            model_name='datosfinancierosempleado',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_financieros', to='RrHh.contrato_laboral'),
        ),
        migrations.AddField(
            model_name='datosfinancierosempleado',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datosfinancierosempleado',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentoadicional',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desc_Adicional', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='descuentoadicional',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentoadicional',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentamayor',
            name='grupo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_mayor', to='Contabilidad.grupocuenta'),
        ),
        migrations.AddField(
            model_name='grupocuenta',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_cuenta', to='Contabilidad.naturaleza'),
        ),
        migrations.AddField(
            model_name='cuentamayor',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_mayor', to='Contabilidad.naturaleza'),
        ),
        migrations.AddField(
            model_name='cuentadetalle',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_detalle', to='Contabilidad.naturaleza'),
        ),
        migrations.AddField(
            model_name='cuentaauxiliar',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_auxiliares', to='Contabilidad.naturaleza'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='asistencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.asistencia'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_nomina', to='RrHh.contrato_laboral'),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedadnomina',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodamnopresta',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rod_No_Prest', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='rodamnopresta',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rodamnopresta',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutavisitas',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_visita', to='RrHh.hoja_vida'),
        ),
        migrations.AddField(
            model_name='rutavisitas',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutavisitas',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='cuenta_mayor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cuentas', to='Contabilidad.cuentamayor'),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cuentas', to='Contabilidad.naturaleza'),
        ),
        migrations.AddField(
            model_name='cuentadetalle',
            name='sub_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_detalle', to='Contabilidad.subcuenta'),
        ),
        migrations.AddField(
            model_name='tabla_precios_rutas',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabla_precios_rutas',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutavisitas',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_visita', to='Contabilidad.tabla_precios_rutas'),
        ),
    ]
