# Generated by Django 5.1.2 on 2024-11-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ActivosFijos', '0002_initial'),
        ('Produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasalida',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aut_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entradasalida',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_p', to='ActivosFijos.estado_actividad'),
        ),
        migrations.AddField(
            model_name='formica',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formica',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_formica',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_formica',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formica',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formica', to='Produccion.grupo_formica'),
        ),
        migrations.AddField(
            model_name='entradasalida',
            name='materiaprima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Produccion.materiaprima'),
        ),
        migrations.AddField(
            model_name='materiaprimausada',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.materiaprima'),
        ),
        migrations.AddField(
            model_name='medidas',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medidas',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='precio_superficie',
            name='Formica_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Superficie', to='Produccion.formica'),
        ),
        migrations.AddField(
            model_name='precio_superficie',
            name='Medida_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Superficie', to='Produccion.medidas'),
        ),
        migrations.AddField(
            model_name='precio_superficie',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='precio_superficie',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procesoproduccion',
            name='materiaprima',
            field=models.ManyToManyField(related_name='procesos', through='Produccion.MateriaPrimaUsada', to='Produccion.materiaprima'),
        ),
        migrations.AddField(
            model_name='materiaprimausada',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.procesoproduccion'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='proceso_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.procesoproduccion'),
        ),
        migrations.AddField(
            model_name='evaluacioncalidad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.productoterminado'),
        ),
        migrations.AddField(
            model_name='entradasalida',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Produccion.productoterminado'),
        ),
    ]
